package com.bytegeeks.protobuf;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Arrays;

import example.simple.Simple.SimpleMessage;

public class SimpleMain {

  public SimpleMain() {
    // TODO Auto-generated constructor stub
  }

  public SimpleMessage init() {
    
    // Use a builder - SimpleMessage builder. Autogenerated code from proto file has this
    SimpleMessage.Builder builder = SimpleMessage.newBuilder();

    // Set fields in that builder
    builder.setId(1)
    .setIsSimple(true)
    .setName("First message");

    //Set Repeated fields
    builder.addSampleList(1)
    .addSampleList(2)
    .addSampleList(3)
    .addAllSampleList(Arrays.asList(4,5,6));

    System.out.println(builder.toString());

    // Generate the message from builder
    SimpleMessage message = builder.build();

    // Try to write the message in field, just to see what is it
    // Open the file too.. it will be binary
    FileOutputStream fos;
    try {
      fos = new FileOutputStream("simple_message.bin");
      message.writeTo(fos);
      fos.close();
    } catch (Exception e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    
    // Send as byte array
    byte bytes[] = message.toByteArray();
    
    // Read back from file..
    // Multiple ways of reading the message.. try with SimpleMessage.
    FileInputStream fis;
    try {
      fis = new FileInputStream("simple_message.bin");
      SimpleMessage msgFromFile = SimpleMessage.parseFrom(fis);
      System.out.println("Message after reading from file: " + msgFromFile);
      fis.close();
    } catch (Exception e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    
    return message;
    
  }
  public static void main(String[] args) {
    SimpleMain main = new SimpleMain();
    main.init();
  }
}
