// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog/blog.proto

package com.proto.blog;

public interface BlogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blog.Blog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string author_id = 2;</code>
   */
  java.lang.String getAuthorId();
  /**
   * <code>string author_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getAuthorIdBytes();

  /**
   * <code>string title = 3;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 4;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 4;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
