// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog/blog.proto

package com.proto.blog;

public interface DeleteBlogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blog.DeleteBlogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string blog_id = 1;</code>
   */
  java.lang.String getBlogId();
  /**
   * <code>string blog_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getBlogIdBytes();
}
