// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog/blog.proto

package com.proto.blog;

public interface UpdateBlogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blog.UpdateBlogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.blog.Blog blog = 1;</code>
   */
  boolean hasBlog();
  /**
   * <code>.blog.Blog blog = 1;</code>
   */
  com.proto.blog.Blog getBlog();
  /**
   * <code>.blog.Blog blog = 1;</code>
   */
  com.proto.blog.BlogOrBuilder getBlogOrBuilder();
}
